spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_server
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080
springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs
api:
  info:
    title: Chat-Server
    version: 1.0.0 RELEASE
    description: Simple Task about Chat Server
    contact-name: Doston
    contact-email: dostonbokhodirov@gmail.com
    contact-url: https://t.me/dostonbokhodirov
    terms-of-count: 10
cloud:
  aws:
    credentials:
      access-key: AKIA4AI4BUQCHBMUZGGS
      secret-key: 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
    region:
      static: us-west-2
bucketName: murodjon